//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinhLuan
    {
        public int ID { get; set; }
        public int IDGame { get; set; }
        public int IDKhach { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
