//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Game()
        {
            this.BinhLuans = new HashSet<BinhLuan>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string UnTitle { get; set; }
        public Nullable<int> IDCategory { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public string MoreImage { get; set; }
        public string Detail { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public Nullable<int> Quatity { get; set; }
        public string LK { get; set; }
    
        public virtual GameCategory GameCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
    }
}
